### ISSUE TITLE
Centrando elementos

### ISSUE THREAD

**Issue by jmcastinheira** [rgmagadan/3enraya#1]
Parece que la solución relative con los dos contenedores no me acaba de convencer, el problema es que si lo intento centrar horizontalmente para un ancho de pantalla de teléfono móvil luego me queda ladeado en la pantalla de ordenador, creo que la solución más sencilla sería crear un único contenedor y centrarlo con position:absolute. Si me creas el contenedor único lo haré

**Comment by rgmagadan** [comment]
Listo.
