### ISSUE TITLE
Solución para distinta linea en jugada  e infoPartida

### ISSUE THREAD

**Issue by jmcastinheira** [rgmagadan/3enraya#2]
Hay dos situaciones diferentes, durante la partida la jugada está metido artificialmente en la linea superior mediante position:relative, esto hace que ignore los márgenes, y por lo tanto los tuve que aumentar, pero al final, en el texto de fin de partida, jugada e infopartida ya están en dos lineas diferentes (porque los separa un <br>) entonces aquí no se ignoran los márgenes, con lo que aparece una separación horizontal mallor, que no tiene sentido. 

Habría que tratar las dos situaciones de la misma forma, o insertar un <br> en las jugadas durante la partida o quitarlo al final

**Comment by rgmagadan** [comment]
Añadidos jugada e infoPartida para todas las posibilidades.
