### ISSUE TITLE
Final de partida

### ISSUE THREAD

**Issue by jmcastinheira** [rgmagadan/3enraya#3]
Considero que al terminar la partida debería quedar todo como empezó, es decir, sin nada; quizás el histórico de partidas, podrías ponerlo en un botón adicional tipo score

**Comment by rgmagadan** [comment]
Pienso que sería raro hacer desaparecer el tablero inmediatamente después de terminar la partida. El usuario debería tener tiempo de revisar el estado del tablero.
Sobre el histórico de partidas creo que no aportaría demasiado aquí, y para que fuese útil, más que la posición final requeriría de poder avanzar y retroceder por los movimientos, lo que implicaría bastante trabajo adicional.
